src/Entity/ContratDa.php
<?php

namespace App\Entity;

use App\Repository\ContratDaRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContratDaRepository::class)]
class ContratDa
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_contrat_da = null;


    #[ORM\ManyToOne(targetEntity: Da::class)]
    #[ORM\JoinColumn(name: 'id_da', referencedColumnName: 'id_da')]
    private Da|null $id_da = null;

    #[ORM\ManyToOne(targetEntity: Production::class)]
    #[ORM\JoinColumn(name: 'id_production', referencedColumnName: 'id_production')]
    private Production|null $id_production = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $creation_contrat = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $titre = null;

    #[ORM\Column(nullable: true)]
    private ?int $nbre_role = null;

    #[ORM\Column(nullable: true)]
    private ?int $montant = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imgFilm = null;


    /**
     * @return int|null
     */
    public function getIdContratDa(): ?int
    {
        return $this->id_contrat_da;
    }

    /**
     * @param int|null $id_contrat_da
     */
    public function setIdContratDa(?int $id_contrat_da): void
    {
        $this->id_contrat_da = $id_contrat_da;
    }

    /**
     * @return Da|null
     */
    public function getIdDa(): ?Da
    {
        return $this->id_da;
    }

    /**
     * @param Da|null $id_da
     */
    public function setIdDa(?Da $id_da): void
    {
        $this->id_da = $id_da;
    }

    /**
     * @return Production|null
     */
    public function getIdProduction(): ?Production
    {
        return $this->id_production;
    }

    /**
     * @param Production|null $id_production
     */
    public function setIdProduction(?Production $id_production): void
    {
        $this->id_production = $id_production;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getCreationContrat(): ?\DateTimeInterface
    {
        return $this->creation_contrat;
    }

    /**
     * @param \DateTimeInterface|null $creation_contrat
     */
    public function setCreationContrat(?\DateTimeInterface $creation_contrat): void
    {
        $this->creation_contrat = $creation_contrat;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    /**
     * @param \DateTimeInterface|null $date_debut
     */
    public function setDateDebut(?\DateTimeInterface $date_debut): void
    {
        $this->date_debut = $date_debut;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    /**
     * @param \DateTimeInterface|null $date_fin
     */
    public function setDateFin(?\DateTimeInterface $date_fin): void
    {
        $this->date_fin = $date_fin;
    }

    /**
     * @return string|null
     */
    public function getTitre(): ?string
    {
        return $this->titre;
    }

    /**
     * @param string|null $titre
     */
    public function setTitre(?string $titre): void
    {
        $this->titre = $titre;
    }

    /**
     * @return int|null
     */
    public function getNbreRole(): ?int
    {
        return $this->nbre_role;
    }

    /**
     * @param int|null $nbre_role
     */
    public function setNbreRole(?int $nbre_role): void
    {
        $this->nbre_role = $nbre_role;
    }

    /**
     * @return int|null
     */
    public function getMontant(): ?int
    {
        return $this->montant;
    }

    /**
     * @param int|null $montant
     */
    public function setMontant(?int $montant): void
    {
        $this->montant = $montant;
    }

    /**
     * @return string|null
     */
    public function getImgFilm(): ?string
    {
        return $this->imgFilm;
    }

    /**
     * @param string|null $imgFilm
     */
    public function setImgFilm(?string $imgFilm): void
    {
        $this->imgFilm = $imgFilm;
    }



}

src/Form/ContratDaType.php
<?php

namespace App\Form;

use App\Entity\ContratDa;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContratDaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('creation_contrat')
            ->add('date_debut')
            ->add('date_fin')
            ->add('titre')
            ->add('nbre_role')
            ->add('id_da')
            ->add('id_production')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ContratDa::class,
        ]);
    }
}

src/Controller/ContratDaController.php
<?php

namespace App\Controller;

use App\Entity\ContratDa;
use App\Form\ContratDaType;
use App\Repository\ContratDaRepository;
use App\Repository\ProductionRepository;
use Doctrine\Persistence\ManagerRegistry;
use PDO;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

#[Route('/contrat/da')]
class ContratDaController extends AbstractController
{


    #[Route('/', name: 'app_contrat_da_index', methods: ['GET'])]
    public function index(ContratDaRepository $contratDaRepository, ManagerRegistry $registry, ProductionRepository $productionRepository,UserInterface $user): Response
    {
        $conn = $registry->getConnection();

        $qb = $conn->createQueryBuilder();
        $qb->select('cd.*, p.libelle')
            ->from('contrat_da', 'cd')
            ->innerJoin('cd', 'production', 'p', 'p.id_production = cd.id_production')
            ->where('cd.id_da = :id_da')
            ->setParameter('id_da', $user->getIdDa());

        $stmt = $qb->execute();

        $contratDa = $stmt->fetchAllAssociative();


        return $this->render('contrat_da/index.html.twig', [
            'contrat_das' => $contratDa,
        ]);
    }

    #[Route('/new', name: 'app_contrat_da_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ContratDaRepository $contratDaRepository): Response
    {
        $contratDa = new ContratDa();
        $form = $this->createForm(ContratDaType::class, $contratDa);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contratDaRepository->save($contratDa, true);

            return $this->redirectToRoute('app_contrat_da_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat_da/new.html.twig', [
            'contrat_da' => $contratDa,
            'form' => $form,
        ]);
    }

    #[Route('/{id_contrat_da}', name: 'app_contrat_da_show', methods: ['GET'])]
    public function show(ContratDa $contratDa): Response
    {
        return $this->render('contrat_da/show.html.twig', [
            'contrat_da' => $contratDa,
        ]);
    }

    #[Route('/{id_contrat_da}/edit', name: 'app_contrat_da_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ContratDa $contratDa, ContratDaRepository $contratDaRepository): Response
    {
        $form = $this->createForm(ContratDaType::class, $contratDa);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contratDaRepository->save($contratDa, true);

            return $this->redirectToRoute('app_contrat_da_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat_da/edit.html.twig', [
            'contrat_da' => $contratDa,
            'form' => $form,
        ]);
    }

    #[Route('/{id_contrat_da}', name: 'app_contrat_da_delete', methods: ['POST'])]
    public function delete(Request $request, ContratDa $contratDa, ContratDaRepository $contratDaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contratDa->getId_contrat_da(), $request->request->get('_token'))) {
            $contratDaRepository->remove($contratDa, true);
        }

        return $this->redirectToRoute('app_contrat_da_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/contrat_da/_delete_form.html.twig
<form method="post" action="{{ path('app_contrat_da_delete', {'id_contrat_da': contrat_da.id_contrat_da}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contrat_da.id_contrat_da) }}">
    <button class="btn">Delete</button>
</form>

templates/contrat_da/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/contrat_da/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ContratDa{% endblock %}

{% block body %}
    <h1>Edit ContratDa</h1>

    {{ include('contrat_da/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contrat_da_index') }}">back to list</a>

    {{ include('contrat_da/_delete_form.html.twig') }}
{% endblock %}

templates/contrat_da/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contrat Directeur Artistique{% endblock %}

{% block body %}

{#    <a style="position: fixed; top: 50%; transform: translateY(-50%);" class="btn btn-primary" href="{{ path('app_contrat_da_new') }}"><i class="bi bi-file-earmark-plus" style="font-size: 2em;"></i></a>#}
    <div class="container d-flex justify-content-center">
    {% for contrat_da in contrat_das %}
        <div class="col-md-2 col-sm-6 mx-4 my-4">
            <div class="card" style="width: 14rem;height:100%" >
              
                <img src="{{ asset('images/Film/' ~ contrat_da.img_film) }}" class="card-img-top" style="height:200px;width: auto;object-fit: cover;"  alt="...">
                <div class="card-body d-flex flex-column justify-content-end">
                    <h5 class="card-title">{{ contrat_da.titre }}</h5>
                    <h6 class="card-title">{{ contrat_da.libelle }}</h6>
                    <p class="card-text">{{ contrat_da.montant }} €</p>
                </div>
{#                <div class="card-body d-flex justify-content-between" style="max-height: 65px">#}
{#                    <a href="{{ path('app_contrat_da_show', {'id_contrat_da': contrat_da.id_contrat_da}) }}"  class="btn btn-primary btn-sm"><i class="bi bi-search"></i> Voir</a>#}
{#                    <a href="{{ path('app_contrat_da_edit', {'id_contrat_da': contrat_da.id_contrat_da}) }}" class="btn btn-primary btn-sm">Modifier</a>#}
{#                </div>#}
            </div>
        </div>
        {% if loop.index % 5 == 0 %}
            </div><div class="container d-flex justify-content-center">
        {% endif %}
    {% else %}
        <tr>
            <td colspan="11">Pas de contrats</td>
        </tr>
    {% endfor %}
    </div>
{% endblock %}
{#{{  }}#}

templates/contrat_da/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ContratDa{% endblock %}

{% block body %}
    <h1>Create new ContratDa</h1>

    {{ include('contrat_da/_form.html.twig') }}

    <a href="{{ path('app_contrat_da_index') }}">back to list</a>
{% endblock %}

templates/contrat_da/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ContratDa{% endblock %}

{% block body %}
    <h1>ContratDa</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_contrat_da</th>
                <td>{{ contrat_da.idContratDa }}</td>
            </tr>
            <tr>
                <th>Creation_contrat</th>
                <td>{{ contrat_da.creationContrat ? contrat_da.creationContrat|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ contrat_da.dateDebut ? contrat_da.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ contrat_da.dateFin ? contrat_da.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ contrat_da.titre }}</td>
            </tr>
            <tr>
                <th>Nbre_role</th>
                <td>{{ contrat_da.nbreRole }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contrat_da_index') }}">back to list</a>

    <a href="{{ path('app_contrat_da_edit', {'id_contrat_da': contrat_da.id_contrat_da}) }}">edit</a>

    {{ include('contrat_da/_delete_form.html.twig') }}
{% endblock %}