src/Entity/Contrat.php
<?php

namespace App\Entity;

use App\Repository\ContratRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContratRepository::class)]
class  Contrat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_contrat = null;

    #[ORM\ManyToOne(targetEntity: Comedien::class)]
    #[ORM\JoinColumn(name: 'id_comedien', referencedColumnName: 'id_comedien')]
    private Comedien|null $id_comedien = null;

    #[ORM\ManyToOne(targetEntity: Da::class)]
    #[ORM\JoinColumn(name: 'id_da', referencedColumnName: 'id_da')]
    private ?int $id_da = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $creation_contrat = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $production = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $titre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_personnage = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    public function getIdContrat(): ?int
    {
        return $this->id_contrat;
    }


    public function getCreationContrat(): ?\DateTimeInterface
    {
        return $this->creation_contrat;
    }

    public function setCreationContrat(?\DateTimeInterface $creation_contrat): self
    {
        $this->creation_contrat = $creation_contrat;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getProduction(): ?string
    {
        return $this->production;
    }

    public function setProduction(?string $production): self
    {
        $this->production = $production;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNomPersonnage(): ?string
    {
        return $this->nom_personnage;
    }

    public function setNomPersonnage(?string $nom_personnage): self
    {
        $this->nom_personnage = $nom_personnage;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
}

src/Entity/ContratComedien.php
<?php

namespace App\Entity;

use App\Repository\ContratComedienRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContratComedienRepository::class)]
class ContratComedien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_contrat_comedien = null;

    #[ORM\ManyToOne(targetEntity: Comedien::class)]
    #[ORM\JoinColumn(name: 'id_comedien', referencedColumnName: 'id_comedien')]
    private Comedien|null $id_comedien = null;

    #[ORM\ManyToOne(targetEntity: Da::class)]
    #[ORM\JoinColumn(name: 'id_da', referencedColumnName: 'id_da')]
    private Da|null $id_da = null;


    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $creation_contrat = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\OneToOne]
    #[ORM\JoinColumn(name: 'id_role', referencedColumnName: 'id_role')]
    private ?Role $id_role = null;

    public function getIdContrat(): ?int
    {
        return $this->id_contrat_comedien;
    }

    /**
     * @return Comedien|null
     */
    public function getIdComedien(): ?Comedien
    {
        return $this->id_comedien;
    }

    /**
     * @param Comedien|null $id_comedien
     */
    public function setIdComedien(?Comedien $id_comedien): void
    {
        $this->id_comedien = $id_comedien;
    }

    /**
     * @return Da|null
     */
    public function getIdDa(): ?Da
    {
        return $this->id_da;
    }

    /**
     * @param Da|null $id_da
     */
    public function setIdDa(?Da $id_da): void
    {
        $this->id_da = $id_da;
    }


    public function getCreationContrat(): ?\DateTimeInterface
    {
        return $this->creation_contrat;
    }

    public function setCreationContrat(?\DateTimeInterface $creation_contrat): self
    {
        $this->creation_contrat = $creation_contrat;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getIdContratComedien(): ?int
    {
        return $this->id_contrat_comedien;
    }

    /**
     * @param int|null $id_contrat_comedien
     */
    public function setIdContratComedien(?int $id_contrat_comedien): void
    {
        $this->id_contrat_comedien = $id_contrat_comedien;
    }


    /**
     * @return Role|null
     */
    public function getIdRole(): ?Role
    {
        return $this->id_role;
    }

    /**
     * @param Role|null $id_role
     */
    public function setIdRole(?Role $id_role): void
    {
        $this->id_role = $id_role;
    }


}

src/Form/ContratComedienType.php
<?php

namespace App\Form;

use App\Entity\ContratComedien;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use App\Entity\Role;
use Doctrine\ORM\EntityManagerInterface;

class ContratComedienType extends AbstractType
{
    private $entityManager;
    private $tokenStorage;

    public function __construct(EntityManagerInterface $entityManager, TokenStorageInterface $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
        $this->entityManager = $entityManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $userId = $this->tokenStorage->getToken()->getUser()->getIdDa();
        $roles = $this->getAvailableRoles($userId);

        $builder
            ->add('date_debut', DateType::class, [
                'widget' => 'single_text',
                'html5' => true,
                'attr' => [
                    'class' => 'form-control input-inline datetimepicker'
                ]
            ])
            ->add('date_fin', DateType::class, [
                'widget' => 'single_text',
                'html5' => true,
                'attr' => [
                    'class' => 'form-control input-inline datetimepicker'
                ],
                'constraints' => [
                    new Callback([$this, 'validateEndDate']),
                ],
            ])
            ->add('id_role', ChoiceType::class, [
                'label' => 'Role',
                'attr' => ['class' => 'form-control mb-3'],
                'choices' => $roles,
                'placeholder' => 'Choisissez un rôle',
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Suivant',
                'attr' => ['class' => 'btn btn-secondary'],
            ]);
    }

    private function getAvailableRoles($userId)
    {
        $entityManager = $this->entityManager;

        $query = $entityManager->createQueryBuilder()
            ->select('r')
            ->from(Role::class, 'r')
            ->leftJoin('r.id_contrat_da', 'c')
            ->andWhere('r NOT IN (
                SELECT ccRole FROM App\Entity\ContratComedien cc JOIN cc.id_role ccRole
            )')
            ->andWhere('c.id_da = :userId')
            ->setParameter('userId', $userId);

        $roles = $query->getQuery()->getResult();

        $rolesChoices = [];

        foreach ($roles as $role) {
            $rolesChoices[$role->getNom()] = $role;
        }

        return $rolesChoices;
    }

    public function validateEndDate($value, ExecutionContextInterface $context)
    {
        $startDate = $context->getRoot()->get('date_debut')->getData();

        if ($value < $startDate) {
            $context->buildViolation('La date de fin doit être supérieure ou égale à la date de début.')
                ->atPath('')
                ->addViolation();
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ContratComedien::class,
            'roles' => [],
        ]);
    }
}

src/Controller/ContratComedienController.php
<?php

namespace App\Controller;

use App\Entity\ContratComedien;
use App\Form\ContratComedienType;
use App\Repository\ComedienRepository;
use App\Repository\ContratComedienRepository;
use App\Repository\DaRepository;
use App\Repository\RoleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

#[Route('/contrat/comedien')]
class ContratComedienController extends AbstractController
{
    #[Route('/', name: 'app_contrat_comedien_index', methods: ['GET'])]
    public function index(ContratComedienRepository $contratComedienRepository,UserInterface $user): Response
    {
        return $this->render('contrat_comedien/index.html.twig', [
            'contrat_comediens' => $contratComedienRepository->findBy(['id_da' => $user->getIdDa() ]),
        ]);
    }

    #[Route('/new/{id_comedien}', name: 'app_contrat_comedien_new', methods: ['GET', 'POST'])]
    public function new(Request $request,RoleRepository $roleRepository, ContratComedienRepository $contratComedienRepository,DaRepository $daRepository, ComedienRepository $comedienRepository,UserInterface $user): Response
    {
        $da = $daRepository->find($user->getIdDa());

        $roles = $roleRepository ->findAllRolesByDa($da ->getIdDa());

        $id_comedien = $request->attributes->get('id_comedien');

        $comedien = $comedienRepository->find($id_comedien);


        $contratComedien = new ContratComedien();

        $form = $this->createForm(ContratComedienType::class, $contratComedien,[
            'roles' => $roles,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $form->getData();

            $contratComedien->setIdDa($da);
            $contratComedien->setIdComedien($comedien);
            $contratComedien->setCreationContrat(new \DateTimeImmutable());

            $contratComedienRepository->save($contratComedien, true);

            return $this->redirectToRoute('app_contrat_comedien_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat_comedien/new.html.twig', [
            'comedien' => $comedien,
            'contrat_comedien' => $contratComedien,
            'form' => $form,
            'roles'=>$roles,
        ]);
    }

    #[Route('/{id_contrat_comedien}', name: 'app_contrat_comedien_show', methods: ['GET'])]
    public function show(ContratComedien $contratComedien): Response
    {
        return $this->render('contrat_comedien/show.html.twig', [
            'contrat_comedien' => $contratComedien,
        ]);
    }

    #[Route('/{id_contrat_comedien}/edit', name: 'app_contrat_comedien_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ContratComedien $contratComedien, ContratComedienRepository $contratComedienRepository): Response
    {
        $form = $this->createForm(ContratComedienType::class, $contratComedien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contratComedienRepository->save($contratComedien, true);

            return $this->redirectToRoute('app_contrat_comedien_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat_comedien/edit.html.twig', [
            'contrat_comedien' => $contratComedien,
            'form' => $form,
        ]);
    }

    #[Route('/{id_contrat_comedien}', name: 'app_contrat_comedien_delete', methods: ['POST'])]
    public function delete(Request $request, ContratComedien $contratComedien, ContratComedienRepository $contratComedienRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contratComedien->getIdContratComedien(), $request->request->get('_token'))) {
            $contratComedienRepository->remove($contratComedien, true);
        }

        return $this->redirectToRoute('app_contrat_comedien_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/contrat_comedien/_delete_form.html.twig
<form method="post" action="{{ path('app_contrat_comedien_delete', {'id_contrat_comedien': contrat_comedien.idContratComedien}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contrat_comedien.idContratComedien) }}">
    <button class="btn btn-danger mx-5">Supprimer</button>
</form>

templates/contrat_comedien/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ContratComedien{% endblock %}

{% block body %}
    <div class="container mt-5 d-flex flex-column justify-center align-items-center">
        <h1>Voulez-vous vraiment supprimez le contrat ?</h1>

    {#    {{ include('contrat_comedien/_form.html.twig', {'button_label': 'Update'}) }}#}
        <div class="d-flex">

            <a class=" btn btn-primary" href="{{ path('app_contrat_comedien_index') }}">Retour à la liste</a>
            {{ include('contrat_comedien/_delete_form.html.twig') }}s
        </div>
    </div>


{% endblock %}

templates/contrat_comedien/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ContratComedien index{% endblock %}
{% block javascripts %}{% endblock %}
{% block body %}

<div class="mt-5" style="height:85vh;width:100vw;">
    <table class="container table table-dark" >
        <thead>
            <tr>
                <th>Id</th>
                <th>Date de début</th>
                <th>Date de fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contrat_comedien in contrat_comediens %}
            <tr>
                <td>{{ contrat_comedien.idContratComedien }}</td>
                <td>{{ contrat_comedien.dateDebut ? contrat_comedien.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ contrat_comedien.dateFin ? contrat_comedien.dateFin|date('Y-m-d') : '' }}</td>





                <td>
                    <a href="{{ path('app_contrat_comedien_show', {'id_contrat_comedien': contrat_comedien.idContratComedien}) }}">show</a>
                    <a href="{{ path('app_contrat_comedien_edit', {'id_contrat_comedien': contrat_comedien.idContratComedien}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/contrat_comedien/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Contrat{% endblock %}
{% block javascripts %}{% endblock %}
{% block body %}

<div class="container container-sm">
    <div class="row justify-content-center align-items-center" style="height:100vh">
        <div class="col-lg-6 col-md-12">
            <h1 class="mb-4">Vous voulez ajouter un contrat pour {{ comedien.prenom }} ?</h1>
            {% if not form.vars.valid %}
                <ul class="alert alert-danger">
                    {# on affiche en premier les erreurs globales (cas classiques) #}
                    {% for error in form.vars.errors %}
                        <li>{{error.message}}</li>
                    {% endfor %}
                    {# ainsi que les erreurs concernant chaque champs #}
                    {% for child in form.children %}
                        {# si le champ à des erreur #}
                        {% if child.vars.errors is defined %}
                            {% for error in child.vars.errors %}
                                <li>{{child.vars.label|upper}} : {{error.message}} </li> {# on ajoute le label du champ devant l'erreur pour plus de précisions. #}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endif %}
            {{ form_start(form) }}
            <div class="row mb-3">
                <div class="cache-message col-sm-12 col-lg-6 mb-3 mb-sm-0">
                    {{ form_row(form.date_debut) }}
                </div>
                <div class="cache-message col-sm-12 col-lg-6">
                    {{ form_row(form.date_fin) }}
                </div>
            {{ form_row(form.id_role) }}

            <div class="cache-message d-flex justify-content-between">
                <a class="btn btn-danger" href="{{ path('app_contrat_comedien_index') }}">Retour à la liste</a>
                {{ form_row(form.submit, {'attr': {'id': 'submit-btn'}}) }}
            </div>

            {{ form_end(form) }}
            </div>

        </div>
    </div>

{% endblock %}

templates/contrat_comedien/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ContratComedien{% endblock %}

{% block body %}
    <h1>ContratComedien</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_contrat_comedien</th>
                <td>{{ contrat_comedien.idContratComedien }}</td>
            </tr>
            <tr>
                <th>Creation_contrat</th>
                <td>{{ contrat_comedien.creationContrat ? contrat_comedien.creationContrat|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ contrat_comedien.dateDebut ? contrat_comedien.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ contrat_comedien.dateFin ? contrat_comedien.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Production</th>
                <td>{{ contrat_comedien.production }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ contrat_comedien.titre }}</td>
            </tr>
            <tr>
                <th>Nom_personnage</th>
                <td>{{ contrat_comedien.nomPersonnage }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ contrat_comedien.prenom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contrat_comedien_index') }}">back to list</a>

    <a href="{{ path('app_contrat_comedien_edit', {'id_contrat_comedien': contrat_comedien.id_contrat_comedien}) }}">edit</a>

    {{ include('contrat_comedien/_delete_form.html.twig') }}
{% endblock %}