src/Entity/Avatar/Comedien.php
<?php

namespace App\Entity\Avatar;

use App\Repository\Avatar\ComedienRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ComedienRepository::class)]
class Comedien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_comedien = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column]
    private ?int $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $age = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sexe = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\OneToOne(inversedBy: 'avatar',targetEntity: Thumbnail::class,cascade: ['persist','remove'])]
    private Thumbnail $thumbnail;

    public function getIdComedien(): ?int
    {
        return $this->id_comedien;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(?int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(?string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getThumbnail(): ?Thumbnail
    {
        return $this->thumbnail;
    }

    public function setThumbnail(Thumbnail $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }
}

src/Entity/Comedien.php
<?php

namespace App\Entity;


use App\Repository\ComedienRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: ComedienRepository::class)]
#[Vich\Uploadable]
class Comedien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_comedien = null;

    #[Vich\UploadableField(mapping: 'avatar_images', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;



    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $age = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sexe = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(nullable: true)]
    private ?int $taux_journalier = null;



    #[ORM\Column(nullable: false)]
    private ?\DateTimeImmutable $updatedAt = null;



    public function getIdComedien(): ?int
    {
        return $this->id_comedien;
    }

    /**
     * @param int|null $id_comedien
     */
    public function setIdComedien(?int $id_comedien): void
    {
        $this->id_comedien = $id_comedien;
    }
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(?int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(?string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
    /**
     * @return int|null
     */
    public function getTauxJournalier(): ?int
    {
        return $this->taux_journalier;
    }

    /**
     * @param int|null $taux_journalier
     */
    public function setTauxJournalier(?int $taux_journalier): void
    {
        $this->taux_journalier = $taux_journalier;
    }
    /**
     * @return \DateTimeImmutable|null
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTimeImmutable|null $updatedAt
     */
    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }
}

src/Form/ComedienType.php
<?php

namespace App\Form;

use App\Entity\Comedien;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\Validator\Constraints\File;


class ComedienType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Nom',
                'attr' => ['class' => 'form-control mb-3'],
                'constraints' => [
                    new Assert\Regex([
                        'pattern' => '/^[a-zA-Z]+$/',
                        'message' => 'Le nom ne peut contenir que des lettres.',
                    ]),
                ],
            ])
            ->add('prenom', TextType::class, [
                'label' => 'Prenom',
                'attr' => ['class' => 'form-control mb-3'],
                'constraints' => [
                    new Assert\Regex([
                        'pattern' => '/^[a-zA-Z]+$/',
                        'message' => 'Le prénom ne peut contenir que des lettres.',
                    ]),
                ],
            ])
            ->add('telephone', TextType::class, [
                'label' => 'Telephone',
                'attr' => ['class' => 'form-control mb-3'],
                'constraints' => [
                    new Regex([
                        'pattern' => '/^[\d\s]*$/',
                        'message' => 'Veuillez saisir uniquement des chiffres.',
                    ]),
                    new Length([
                        'min' => 14,
                        'max' => 14,

                    ]),
                ],
            ])
            ->add('email', EmailType::class, [
                'label' => 'email',
                'attr' => ['class' => 'form-control mb-3'],
            ])
            ->add('age', IntegerType::class, [
                'label' => 'Age',
                'attr' => ['class' => 'form-control mb-3'],
                'constraints' => [
                    new Range([
                        'min' => 5,
                        'max' => 95,

                    ]),
                ],

            ])
            ->add('taux_journalier', IntegerType::class, [
                'label' => 'Taux journalier',
                'attr' => ['class' => 'form-control mb-3'],
                'constraints' => [
                    new Range([
                        'min' => 90,
                        'max' => 1000,

                    ]),
                ],

            ])
            ->add('sexe', ChoiceType::class, [
                'label' => 'Sexe',
                'attr' => ['class' => 'form-select mb-3'],
                'choices' => [
                    'Homme' => 'Homme',
                    'Femme' => 'Femme',
                ],
            ])
            ->add('type', ChoiceType::class, [
                'label' => 'Type',
                'attr' => ['class' => 'form-select mb-3'],
                'choices' => [
                    'Caucasiens' => 'Caucasiens',
                    'Afro-américains' => 'Afro-américains',
                    'Asiatiques ' => 'Asiatiques',
                    'Hispaniques/Latinos' => 'Hispaniques/Latinos',
                    'Moyen-Orientaux ' => 'Moyen-Orientaux',
                    'Amérindiens' => 'Amérindiens ',
                ],
            ])
            ->add('imageFile', FileType::class, [
                'label' => 'Avatar',
                'label_attr' => [
                    'class' => 'form-label mt-4',
                ],
                'attr' => ['class' => 'form-control mb-3'],
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'image/*',
                        ],

                    ]),
                ],
            ])

        ;

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comedien::class,
        ]);
    }
}

src/Controller/ComedienController.php
<?php

namespace App\Controller;

use App\Entity\Comedien;
use App\Form\ComedienType;
use App\Repository\ComedienRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;

#[Route('/comedien')]
class ComedienController extends AbstractController
{
    public function __construct(
        ManagerRegistry $doctrine
    )
    {
        $this->doctrine = $doctrine;
    }
    #[Route('/', name: 'app_comedien_index', methods: ['GET'])]
    public function index(ComedienRepository $comedienRepository): Response
    {
        return $this->render('comedien/index.html.twig', [
            'comediens' => $comedienRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_comedien_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ComedienRepository $comedienRepository,ManagerRegistry $doctrine): Response
    {

        $comedien = new Comedien();
        $form = $this->createForm(ComedienType::class, $comedien);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $comedienRepository->save($comedien, true);

            return $this->redirectToRoute('app_comedien_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('comedien/new.html.twig', [
            'comedien' => $comedien,
            'form' => $form,
        ]);
    }

    #[Route('/{id_comedien}', name: 'app_comedien_show', methods: ['GET'])]
    public function show(Comedien $comedien): Response
    {
        return $this->render('comedien/show.html.twig', [
            'comedien' => $comedien,
        ]);
    }

    #[Route('/{id_comedien}/edit', name: 'app_comedien_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comedien $comedien, ComedienRepository $comedienRepository): Response
    {
        $form = $this->createForm(ComedienType::class, $comedien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comedienRepository->save($comedien, true);

            return $this->redirectToRoute('app_comedien_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('comedien/edit.html.twig', [
            'comedien' => $comedien,
            'form' => $form,
        ]);
    }

    #[Route('/{id_comedien}', name: 'app_comedien_delete', methods: ['POST'])]
    public function delete(Request $request, Comedien $comedien, ComedienRepository $comedienRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comedien->getIdComedien(), $request->request->get('_token'))) {
            $comedienRepository->remove($comedien, true);
        }

        return $this->redirectToRoute('app_comedien_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/comedien/_delete_form.html.twig
<form method="post" action="{{ path('app_comedien_delete', {'id_comedien': comedien.idComedien}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comedien.idComedien) }}">
    <button class="btn">Delete</button>
</form>

templates/comedien/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<div class="d-flex justify-content-between">
    <a class="btn btn-danger" href="{{ path('app_comedien_index') }}">Retour à la liste</a>
    <button class="btn btn-secondary">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/comedien/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Comedien{% endblock %}

{% block body %}

    <div class="container-sm mt-3">
    {{ include('comedien/_form.html.twig', {'button_label': 'Editer'}) }}


    </div>

{#   {{ include('comedien/_delete_form.html.twig') }}#}
{% endblock %}

templates/comedien/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comediens{% endblock %}

{% block body %}

    <a style="position: fixed; top: 50%; transform: translateY(-50%);" class="btn btn-primary" href="{{ path('app_comedien_new') }}"><i class="bi bi-person-add icon-white" style="font-size: 2em;"></i></a>
    <div class="container d-flex justify-content-center">
    {% for comedien in comediens %}
        <div class="col-md-2 col-sm-6 mx-4 my-4">
            <div class="card" style="width: 14rem;">
                <img src="{{ asset('images/avatar/' ~ comedien.imageName) }}" class="card-img-top" style="height:200px;width: auto"  alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ comedien.prenom }} {{ comedien.nom }}</h5>
                    <p class="card-text">{{ comedien.tauxjournalier }} € / Jour</p>
                </div>
                <div class="card-body d-flex justify-content-between">
                    <a href="{{ path('app_contrat_comedien_new', {'id_comedien': comedien.idComedien}) }}" class="btn btn-primary btn-sm"><i class="bi bi-file-earmark-plus"></i> Contrat</a>
                    <a class='btn btn-primary btn-sm' href="{{ path('app_comedien_show', {'id_comedien': comedien.idComedien}) }}"><i class="bi bi-search"></i> Voir</a>
                </div>
            </div>
        </div>
        {% if loop.index % 5 == 0 %}
            </div><div class="container d-flex justify-content-center">
        {% endif %}
    {% else %}
        <tr>
            <td colspan="11">Pas de comédiens</td>
        </tr>
    {% endfor %}
    </div>






{#                <td>#}

{#                    <a href="{{ path('app_comedien_edit', {'id_comedien': comedien.id_comedien}) }}">edit</a>#}
{#                </td>#}


{% endblock %}

templates/comedien/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Comédien{% endblock %}

{% block body %}
    <div class="container container-sm">
        <div class="row justify-content-center align-items-center" style="height:100vh">
            <div class="col-lg-6 col-md-12">
                {% if not form.vars.valid %}
                    <ul class="alert alert-danger">
                        {# on affiche en premier les erreurs globales (cas classiques) #}
                        {% for error in form.vars.errors %}
                            <li>{{error.message}}</li>
                        {% endfor %}
                        {# ainsi que les erreurs concernant chaque champs #}
                        {% for child in form.children %}
                            {# si le champ à des erreur #}
                            {% if child.vars.errors is defined %}
                                {% for error in child.vars.errors %}
                                    <li>{{child.vars.label|upper}} : {{error.message}} </li> {# on ajoute le label du champ devant l'erreur pour plus de précisions. #}
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
                <h1 class="mb-4">Nouveau comédien</h1>

                {{ form_start(form) }}


                <div class="row mb-3">
                    <div class="cache-message col-sm-12 col-lg-6 mb-3 mb-sm-0">
                        {{ form_row(form.nom) }}

                    </div>

                    <div class="cache-message col-sm-12 col-lg-6">
                        {{ form_row(form.prenom) }}

                    </div>
                </div>

                <div class="row mb-3">
                    <div class="cache-message col-sm-12 col-lg-6 mb-3 mb-sm-0">
                        {{ form_row(form.telephone, {'attr': {'data-telephone': ''}}) }}
                    </div>

                    <div class="cache-message col-sm-12 col-lg-6">
                        {{ form_row(form.email) }}

                    </div>
                </div>

                <div class="row mb-3">
                    <div class="cache-message col-sm-12 col-lg-6 mb-3 mb-sm-0">
                        {{ form_row(form.age) }}

                    </div>

                    <div class="cache-message col-sm-12 col-lg-6">
                        {{ form_row(form.sexe) }}

                    </div>
                </div>

                {{ form_row(form.taux_journalier) }}

                {{ form_row(form.type) }}

                {{ form_row(form.imageFile)}}


                <div class="cache-message ">

{#                    {{ form_row(form.submit) }}#}
                    {{ include('comedien/_form.html.twig', {'button_label': 'Ajouter'}) }}
                </div>

                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/comedien/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comedien{% endblock %}

{% block body %}

    <div class=" showContainer mt-5 d-flex align-items-center justify-content-center pt-5" >

        <div class="col text-center">
            <img class="col" src="{{ asset('images/avatar/' ~ comedien.imageName) }}"  style= "height:300px" alt="">
        </div>

        <div class="col showContainerText ">
            <h1>{{ comedien.nom }} {{ comedien.prenom }}</h1>
            <h3>{{ comedien.telephone }}</h3>
            <h3>{{ comedien.age }} ans</h3>
            <h3>{{ comedien.sexe }}</h3>
            <h3>{{ comedien.type }}</h3>
            <h3>{{ comedien.tauxjournalier }} € / Jour</h3>
            <div class="d-flex ">
                <a class=" col-4  btn btn-primary " href="{{ path('app_comedien_index') }}">Retour à la liste</a>
                <a class=" col-4  btn btn-primary mx-5" href="{{ path('app_comedien_edit', {'id_comedien': comedien.idComedien}) }}">Modifier</a>

            </div>
             </div>
    </div>



{#    {{ include('comedien/_delete_form.html.twig') }}#}
{% endblock %}